<a href="https://colab.research.google.com/github/leandroclv/polars_udemy/blob/main/introducao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import polars as pl

In [25]:
#Criando o dataframe
df = pl.DataFrame({
    'nome': ['Alice', 'Bob', 'Charlie', 'David'],
    'idade': [25, 30, 35, 40],
    'cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Porto Alegre']
})

In [26]:
df

shape: (4, 3)
┌─────────┬───────┬────────────────┐
│ nome    ┆ idade ┆ cidade         │
│ ---     ┆ ---   ┆ ---            │
│ str     ┆ i64   ┆ str            │
╞═════════╪═══════╪════════════════╡
│ Alice   ┆ 25    ┆ São Paulo      │
│ Bob     ┆ 30    ┆ Rio de Janeiro │
│ Charlie ┆ 35    ┆ Belo Horizonte │
│ David   ┆ 40    ┆ Porto Alegre   │
└─────────┴───────┴────────────────┘

In [27]:
#Exemplo de leitura csv público
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv'
df = pl.read_csv(url)
df.head()

shape: (5, 7)
┌────────────┬──────┬────────┬────────┬─────┬────────┬──────┐
│ total_bill ┆ tip  ┆ sex    ┆ smoker ┆ day ┆ time   ┆ size │
│ ---        ┆ ---  ┆ ---    ┆ ---    ┆ --- ┆ ---    ┆ ---  │
│ f64        ┆ f64  ┆ str    ┆ str    ┆ str ┆ str    ┆ i64  │
╞════════════╪══════╪════════╪════════╪═════╪════════╪══════╡
│ 16.99      ┆ 1.01 ┆ Female ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 10.34      ┆ 1.66 ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 3    │
│ 21.01      ┆ 3.5  ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 3    │
│ 23.68      ┆ 3.31 ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 24.59      ┆ 3.61 ┆ Female ┆ No     ┆ Sun ┆ Dinner ┆ 4    │
└────────────┴──────┴────────┴────────┴─────┴────────┴──────┘

In [28]:
#Ver colunas
print(df.columns)

['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

In [29]:
#Ver tipo de dados
print(df.dtypes)

[Float64, Float64, String, String, String, String, Int64]

In [30]:
#Contar numeros de linhas
print(df.shape)

(244, 7)

In [31]:
#Estatísticas descritivas
print(df.describe())

shape: (9, 8)
┌────────────┬────────────┬──────────┬────────┬────────┬──────┬────────┬──────────┐
│ statistic  ┆ total_bill ┆ tip      ┆ sex    ┆ smoker ┆ day  ┆ time   ┆ size     │
│ ---        ┆ ---        ┆ ---      ┆ ---    ┆ ---    ┆ ---  ┆ ---    ┆ ---      │
│ str        ┆ f64        ┆ f64      ┆ str    ┆ str    ┆ str  ┆ str    ┆ f64      │
╞════════════╪════════════╪══════════╪════════╪════════╪══════╪════════╪══════════╡
│ count      ┆ 244.0      ┆ 244.0    ┆ 244    ┆ 244    ┆ 244  ┆ 244    ┆ 244.0    │
│ null_count ┆ 0.0        ┆ 0.0      ┆ 0      ┆ 0      ┆ 0    ┆ 0      ┆ 0.0      │
│ mean       ┆ 19.785943  ┆ 2.998279 ┆ null   ┆ null   ┆ null ┆ null   ┆ 2.569672 │
│ std        ┆ 8.902412   ┆ 1.383638 ┆ null   ┆ null   ┆ null ┆ null   ┆ 0.9511   │
│ min        ┆ 3.07       ┆ 1.0      ┆ Female ┆ No     ┆ Fri  ┆ Dinner ┆ 1.0      │
│ 25%        ┆ 13.37      ┆ 2.0      ┆ null   ┆ null   ┆ null ┆ null   ┆ 2.0      │
│ 50%        ┆ 17.81      ┆ 2.92     ┆ null   ┆ null   ┆ null ┆ null   ┆ 2.0      │
│ 75%        ┆ 24.08      ┆ 3.55     ┆ null   ┆ null   ┆ null ┆ null   ┆ 3.0      │
│ max        ┆ 50.81      ┆ 10.0     ┆ Male   ┆ Yes    ┆ Thur ┆ Lunch  ┆ 6.0      │
└────────────┴────────────┴──────────┴────────┴────────┴──────┴────────┴──────────┘

In [32]:
#Selecionar colunas
df.select(['total_bill','tip']).head()

shape: (5, 2)
┌────────────┬──────┐
│ total_bill ┆ tip  │
│ ---        ┆ ---  │
│ f64        ┆ f64  │
╞════════════╪══════╡
│ 16.99      ┆ 1.01 │
│ 10.34      ┆ 1.66 │
│ 21.01      ┆ 3.5  │
│ 23.68      ┆ 3.31 │
│ 24.59      ┆ 3.61 │
└────────────┴──────┘

In [33]:
#Filtrar dados
df.filter(pl.col('total_bill') > 10).head()

shape: (5, 7)
┌────────────┬──────┬────────┬────────┬─────┬────────┬──────┐
│ total_bill ┆ tip  ┆ sex    ┆ smoker ┆ day ┆ time   ┆ size │
│ ---        ┆ ---  ┆ ---    ┆ ---    ┆ --- ┆ ---    ┆ ---  │
│ f64        ┆ f64  ┆ str    ┆ str    ┆ str ┆ str    ┆ i64  │
╞════════════╪══════╪════════╪════════╪═════╪════════╪══════╡
│ 16.99      ┆ 1.01 ┆ Female ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 10.34      ┆ 1.66 ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 3    │
│ 21.01      ┆ 3.5  ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 3    │
│ 23.68      ┆ 3.31 ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 24.59      ┆ 3.61 ┆ Female ┆ No     ┆ Sun ┆ Dinner ┆ 4    │
└────────────┴──────┴────────┴────────┴─────┴────────┴──────┘

In [34]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [35]:
import pandas as pd

In [36]:
#Criando um dataframe com pandas
df_pandas = pd.DataFrame({
    'produto': ['arroz', 'feijão', 'macarrão'],
    'quantidade': [50, 120, 130 ]
})

In [37]:
df_pandas

    produto  quantidade
0     arroz          50
1    feijão         120
2  macarrão         130

In [38]:
#Converter para polars
df_polars = pl.from_pandas(df_pandas)
df_polars

shape: (3, 2)
┌──────────┬────────────┐
│ produto  ┆ quantidade │
│ ---      ┆ ---        │
│ str      ┆ i64        │
╞══════════╪════════════╡
│ arroz    ┆ 50         │
│ feijão   ┆ 120        │
│ macarrão ┆ 130        │
└──────────┴────────────┘

In [39]:
display(df_polars)

shape: (3, 2)
┌──────────┬────────────┐
│ produto  ┆ quantidade │
│ ---      ┆ ---        │
│ str      ┆ i64        │
╞══════════╪════════════╡
│ arroz    ┆ 50         │
│ feijão   ┆ 120        │
│ macarrão ┆ 130        │
└──────────┴────────────┘

In [40]:
#Voltando para pandas
df_pandas_again = df_polars.to_pandas()
df_pandas_again

    produto  quantidade
0     arroz          50
1    feijão         120
2  macarrão         130

In [41]:
import time

In [44]:
#Leitura com pandas
start = time.time()
df_pandas_time = pd.read_csv(url)
print(f'Pandas read_csv: {round(time.time() - start,4)} segundos')

Pandas read_csv: 0.0946 segundos

In [45]:
#leitura com polars
start = time.time()
df_polars_time = pl.read_csv(url)
print(f'Polars read_csv: {round(time.time() - start,4)} segundos')

Polars read_csv: 0.0887 segundos