<a href="https://colab.research.google.com/github/leandroclv/polars_udemy/blob/main/introducao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import polars as pl

In [25]:
#Criando o dataframe
df = pl.DataFrame({
    'nome': ['Alice', 'Bob', 'Charlie', 'David'],
    'idade': [25, 30, 35, 40],
    'cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Porto Alegre']
})

In [26]:
df

shape: (4, 3)
┌─────────┬───────┬────────────────┐
│ nome    ┆ idade ┆ cidade         │
│ ---     ┆ ---   ┆ ---            │
│ str     ┆ i64   ┆ str            │
╞═════════╪═══════╪════════════════╡
│ Alice   ┆ 25    ┆ São Paulo      │
│ Bob     ┆ 30    ┆ Rio de Janeiro │
│ Charlie ┆ 35    ┆ Belo Horizonte │
│ David   ┆ 40    ┆ Porto Alegre   │
└─────────┴───────┴────────────────┘

In [27]:
#Exemplo de leitura csv público
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv'
df = pl.read_csv(url)
df.head()

shape: (5, 7)
┌────────────┬──────┬────────┬────────┬─────┬────────┬──────┐
│ total_bill ┆ tip  ┆ sex    ┆ smoker ┆ day ┆ time   ┆ size │
│ ---        ┆ ---  ┆ ---    ┆ ---    ┆ --- ┆ ---    ┆ ---  │
│ f64        ┆ f64  ┆ str    ┆ str    ┆ str ┆ str    ┆ i64  │
╞════════════╪══════╪════════╪════════╪═════╪════════╪══════╡
│ 16.99      ┆ 1.01 ┆ Female ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 10.34      ┆ 1.66 ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 3    │
│ 21.01      ┆ 3.5  ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 3    │
│ 23.68      ┆ 3.31 ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 24.59      ┆ 3.61 ┆ Female ┆ No     ┆ Sun ┆ Dinner ┆ 4    │
└────────────┴──────┴────────┴────────┴─────┴────────┴──────┘

In [28]:
#Ver colunas
print(df.columns)

['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

In [29]:
#Ver tipo de dados
print(df.dtypes)

[Float64, Float64, String, String, String, String, Int64]

In [30]:
#Contar numeros de linhas
print(df.shape)

(244, 7)

In [31]:
#Estatísticas descritivas
print(df.describe())

shape: (9, 8)
┌────────────┬────────────┬──────────┬────────┬────────┬──────┬────────┬──────────┐
│ statistic  ┆ total_bill ┆ tip      ┆ sex    ┆ smoker ┆ day  ┆ time   ┆ size     │
│ ---        ┆ ---        ┆ ---      ┆ ---    ┆ ---    ┆ ---  ┆ ---    ┆ ---      │
│ str        ┆ f64        ┆ f64      ┆ str    ┆ str    ┆ str  ┆ str    ┆ f64      │
╞════════════╪════════════╪══════════╪════════╪════════╪══════╪════════╪══════════╡
│ count      ┆ 244.0      ┆ 244.0    ┆ 244    ┆ 244    ┆ 244  ┆ 244    ┆ 244.0    │
│ null_count ┆ 0.0        ┆ 0.0      ┆ 0      ┆ 0      ┆ 0    ┆ 0      ┆ 0.0      │
│ mean       ┆ 19.785943  ┆ 2.998279 ┆ null   ┆ null   ┆ null ┆ null   ┆ 2.569672 │
│ std        ┆ 8.902412   ┆ 1.383638 ┆ null   ┆ null   ┆ null ┆ null   ┆ 0.9511   │
│ min        ┆ 3.07       ┆ 1.0      ┆ Female ┆ No     ┆ Fri  ┆ Dinner ┆ 1.0      │
│ 25%        ┆ 13.37      ┆ 2.0      ┆ null   ┆ null   ┆ null ┆ null   ┆ 2.0      │
│ 50%        ┆ 17.81      ┆ 2.92     ┆ null   ┆ null   ┆ null ┆ null   ┆ 2.0      │
│ 75%        ┆ 24.08      ┆ 3.55     ┆ null   ┆ null   ┆ null ┆ null   ┆ 3.0      │
│ max        ┆ 50.81      ┆ 10.0     ┆ Male   ┆ Yes    ┆ Thur ┆ Lunch  ┆ 6.0      │
└────────────┴────────────┴──────────┴────────┴────────┴──────┴────────┴──────────┘

In [32]:
#Selecionar colunas
df.select(['total_bill','tip']).head()

shape: (5, 2)
┌────────────┬──────┐
│ total_bill ┆ tip  │
│ ---        ┆ ---  │
│ f64        ┆ f64  │
╞════════════╪══════╡
│ 16.99      ┆ 1.01 │
│ 10.34      ┆ 1.66 │
│ 21.01      ┆ 3.5  │
│ 23.68      ┆ 3.31 │
│ 24.59      ┆ 3.61 │
└────────────┴──────┘

In [33]:
#Filtrar dados
df.filter(pl.col('total_bill') > 10).head()

shape: (5, 7)
┌────────────┬──────┬────────┬────────┬─────┬────────┬──────┐
│ total_bill ┆ tip  ┆ sex    ┆ smoker ┆ day ┆ time   ┆ size │
│ ---        ┆ ---  ┆ ---    ┆ ---    ┆ --- ┆ ---    ┆ ---  │
│ f64        ┆ f64  ┆ str    ┆ str    ┆ str ┆ str    ┆ i64  │
╞════════════╪══════╪════════╪════════╪═════╪════════╪══════╡
│ 16.99      ┆ 1.01 ┆ Female ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 10.34      ┆ 1.66 ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 3    │
│ 21.01      ┆ 3.5  ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 3    │
│ 23.68      ┆ 3.31 ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 24.59      ┆ 3.61 ┆ Female ┆ No     ┆ Sun ┆ Dinner ┆ 4    │
└────────────┴──────┴────────┴────────┴─────┴────────┴──────┘

In [34]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [35]:
import pandas as pd

In [36]:
#Criando um dataframe com pandas
df_pandas = pd.DataFrame({
    'produto': ['arroz', 'feijão', 'macarrão'],
    'quantidade': [50, 120, 130 ]
})

In [37]:
df_pandas

    produto  quantidade
0     arroz          50
1    feijão         120
2  macarrão         130

In [38]:
#Converter para polars
df_polars = pl.from_pandas(df_pandas)
df_polars

shape: (3, 2)
┌──────────┬────────────┐
│ produto  ┆ quantidade │
│ ---      ┆ ---        │
│ str      ┆ i64        │
╞══════════╪════════════╡
│ arroz    ┆ 50         │
│ feijão   ┆ 120        │
│ macarrão ┆ 130        │
└──────────┴────────────┘

In [39]:
display(df_polars)

shape: (3, 2)
┌──────────┬────────────┐
│ produto  ┆ quantidade │
│ ---      ┆ ---        │
│ str      ┆ i64        │
╞══════════╪════════════╡
│ arroz    ┆ 50         │
│ feijão   ┆ 120        │
│ macarrão ┆ 130        │
└──────────┴────────────┘

In [40]:
#Voltando para pandas
df_pandas_again = df_polars.to_pandas()
df_pandas_again

    produto  quantidade
0     arroz          50
1    feijão         120
2  macarrão         130

In [41]:
import time

In [44]:
#Leitura com pandas
start = time.time()
df_pandas_time = pd.read_csv(url)
print(f'Pandas read_csv: {round(time.time() - start,4)} segundos')

Pandas read_csv: 0.0946 segundos

In [45]:
#leitura com polars
start = time.time()
df_polars_time = pl.read_csv(url)
print(f'Polars read_csv: {round(time.time() - start,4)} segundos')

Polars read_csv: 0.0887 segundos

In [48]:
#selecionando colunas específicas
df.select(['total_bill','tip']).head()

shape: (5, 2)
┌────────────┬──────┐
│ total_bill ┆ tip  │
│ ---        ┆ ---  │
│ f64        ┆ f64  │
╞════════════╪══════╡
│ 16.99      ┆ 1.01 │
│ 10.34      ┆ 1.66 │
│ 21.01      ┆ 3.5  │
│ 23.68      ┆ 3.31 │
│ 24.59      ┆ 3.61 │
└────────────┴──────┘

In [53]:
#Usando expressões (permite operações no select)
df.select([pl.col('total_bill'), (pl.col('tip') / pl.col('total_bill')*100).alias('percent_gorgeta')]).head()

shape: (5, 2)
┌────────────┬─────────────────┐
│ total_bill ┆ percent_gorgeta │
│ ---        ┆ ---             │
│ f64        ┆ f64             │
╞════════════╪═════════════════╡
│ 16.99      ┆ 5.944673        │
│ 10.34      ┆ 16.054159       │
│ 21.01      ┆ 16.658734       │
│ 23.68      ┆ 13.978041       │
│ 24.59      ┆ 14.680765       │
└────────────┴─────────────────┘

In [59]:
#filtrando dados declientes de deixaram uma gorgeta maior que 20%
df.filter(pl.col('tip')/pl.col('total_bill')*100 > 20).head()

shape: (5, 7)
┌────────────┬──────┬────────┬────────┬─────┬────────┬──────┐
│ total_bill ┆ tip  ┆ sex    ┆ smoker ┆ day ┆ time   ┆ size │
│ ---        ┆ ---  ┆ ---    ┆ ---    ┆ --- ┆ ---    ┆ ---  │
│ f64        ┆ f64  ┆ str    ┆ str    ┆ str ┆ str    ┆ i64  │
╞════════════╪══════╪════════╪════════╪═════╪════════╪══════╡
│ 8.77       ┆ 2.0  ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 14.78      ┆ 3.23 ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 14.83      ┆ 3.02 ┆ Female ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 16.29      ┆ 3.71 ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 3    │
│ 16.97      ┆ 3.5  ┆ Female ┆ No     ┆ Sun ┆ Dinner ┆ 3    │
└────────────┴──────┴────────┴────────┴─────┴────────┴──────┘

In [58]:
df.filter(pl.col('day') == 'Sun').head()

shape: (5, 7)
┌────────────┬──────┬────────┬────────┬─────┬────────┬──────┐
│ total_bill ┆ tip  ┆ sex    ┆ smoker ┆ day ┆ time   ┆ size │
│ ---        ┆ ---  ┆ ---    ┆ ---    ┆ --- ┆ ---    ┆ ---  │
│ f64        ┆ f64  ┆ str    ┆ str    ┆ str ┆ str    ┆ i64  │
╞════════════╪══════╪════════╪════════╪═════╪════════╪══════╡
│ 16.99      ┆ 1.01 ┆ Female ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 10.34      ┆ 1.66 ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 3    │
│ 21.01      ┆ 3.5  ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 3    │
│ 23.68      ┆ 3.31 ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 24.59      ┆ 3.61 ┆ Female ┆ No     ┆ Sun ┆ Dinner ┆ 4    │
└────────────┴──────┴────────┴────────┴─────┴────────┴──────┘

In [61]:
df = df.with_columns([(pl.col('tip')/pl.col('total_bill')*100).alias('percent_gorgeta'),
                      (pl.col('total_bill') + pl.col('tip')).alias('total_pago')])
df.head()

shape: (5, 9)
┌────────────┬──────┬────────┬────────┬───┬────────┬──────┬─────────────────┬────────────┐
│ total_bill ┆ tip  ┆ sex    ┆ smoker ┆ … ┆ time   ┆ size ┆ percent_gorgeta ┆ total_pago │
│ ---        ┆ ---  ┆ ---    ┆ ---    ┆   ┆ ---    ┆ ---  ┆ ---             ┆ ---        │
│ f64        ┆ f64  ┆ str    ┆ str    ┆   ┆ str    ┆ i64  ┆ f64             ┆ f64        │
╞════════════╪══════╪════════╪════════╪═══╪════════╪══════╪═════════════════╪════════════╡
│ 16.99      ┆ 1.01 ┆ Female ┆ No     ┆ … ┆ Dinner ┆ 2    ┆ 5.944673        ┆ 18.0       │
│ 10.34      ┆ 1.66 ┆ Male   ┆ No     ┆ … ┆ Dinner ┆ 3    ┆ 16.054159       ┆ 12.0       │
│ 21.01      ┆ 3.5  ┆ Male   ┆ No     ┆ … ┆ Dinner ┆ 3    ┆ 16.658734       ┆ 24.51      │
│ 23.68      ┆ 3.31 ┆ Male   ┆ No     ┆ … ┆ Dinner ┆ 2    ┆ 13.978041       ┆ 26.99      │
│ 24.59      ┆ 3.61 ┆ Female ┆ No     ┆ … ┆ Dinner ┆ 4    ┆ 14.680765       ┆ 28.2       │
└────────────┴──────┴────────┴────────┴───┴────────┴──────┴─────────────────┴────────────┘

In [62]:
#Ordenando dados
df.sort('total_bill').head()

shape: (5, 9)
┌────────────┬──────┬────────┬────────┬───┬────────┬──────┬─────────────────┬────────────┐
│ total_bill ┆ tip  ┆ sex    ┆ smoker ┆ … ┆ time   ┆ size ┆ percent_gorgeta ┆ total_pago │
│ ---        ┆ ---  ┆ ---    ┆ ---    ┆   ┆ ---    ┆ ---  ┆ ---             ┆ ---        │
│ f64        ┆ f64  ┆ str    ┆ str    ┆   ┆ str    ┆ i64  ┆ f64             ┆ f64        │
╞════════════╪══════╪════════╪════════╪═══╪════════╪══════╪═════════════════╪════════════╡
│ 3.07       ┆ 1.0  ┆ Female ┆ Yes    ┆ … ┆ Dinner ┆ 1    ┆ 32.57329        ┆ 4.07       │
│ 5.75       ┆ 1.0  ┆ Female ┆ Yes    ┆ … ┆ Dinner ┆ 2    ┆ 17.391304       ┆ 6.75       │
│ 7.25       ┆ 1.0  ┆ Female ┆ No     ┆ … ┆ Dinner ┆ 1    ┆ 13.793103       ┆ 8.25       │
│ 7.25       ┆ 5.15 ┆ Male   ┆ Yes    ┆ … ┆ Dinner ┆ 2    ┆ 71.034483       ┆ 12.4       │
│ 7.51       ┆ 2.0  ┆ Male   ┆ No     ┆ … ┆ Lunch  ┆ 2    ┆ 26.631158       ┆ 9.51       │
└────────────┴──────┴────────┴────────┴───┴────────┴──────┴─────────────────┴────────────┘

In [63]:
df.sort('total_bill', descending=True).head()

shape: (5, 9)
┌────────────┬──────┬──────┬────────┬───┬────────┬──────┬─────────────────┬────────────┐
│ total_bill ┆ tip  ┆ sex  ┆ smoker ┆ … ┆ time   ┆ size ┆ percent_gorgeta ┆ total_pago │
│ ---        ┆ ---  ┆ ---  ┆ ---    ┆   ┆ ---    ┆ ---  ┆ ---             ┆ ---        │
│ f64        ┆ f64  ┆ str  ┆ str    ┆   ┆ str    ┆ i64  ┆ f64             ┆ f64        │
╞════════════╪══════╪══════╪════════╪═══╪════════╪══════╪═════════════════╪════════════╡
│ 50.81      ┆ 10.0 ┆ Male ┆ Yes    ┆ … ┆ Dinner ┆ 3    ┆ 19.681165       ┆ 60.81      │
│ 48.33      ┆ 9.0  ┆ Male ┆ No     ┆ … ┆ Dinner ┆ 4    ┆ 18.621974       ┆ 57.33      │
│ 48.27      ┆ 6.73 ┆ Male ┆ No     ┆ … ┆ Dinner ┆ 4    ┆ 13.942407       ┆ 55.0       │
│ 48.17      ┆ 5.0  ┆ Male ┆ No     ┆ … ┆ Dinner ┆ 6    ┆ 10.379905       ┆ 53.17      │
│ 45.35      ┆ 3.5  ┆ Male ┆ Yes    ┆ … ┆ Dinner ┆ 3    ┆ 7.717751        ┆ 48.85      │
└────────────┴──────┴──────┴────────┴───┴────────┴──────┴─────────────────┴────────────┘

In [64]:
df.sort(['day', 'total_bill'], descending=[False, True]).head()

shape: (5, 9)
┌────────────┬──────┬────────┬────────┬───┬────────┬──────┬─────────────────┬────────────┐
│ total_bill ┆ tip  ┆ sex    ┆ smoker ┆ … ┆ time   ┆ size ┆ percent_gorgeta ┆ total_pago │
│ ---        ┆ ---  ┆ ---    ┆ ---    ┆   ┆ ---    ┆ ---  ┆ ---             ┆ ---        │
│ f64        ┆ f64  ┆ str    ┆ str    ┆   ┆ str    ┆ i64  ┆ f64             ┆ f64        │
╞════════════╪══════╪════════╪════════╪═══╪════════╪══════╪═════════════════╪════════════╡
│ 40.17      ┆ 4.73 ┆ Male   ┆ Yes    ┆ … ┆ Dinner ┆ 4    ┆ 11.774956       ┆ 44.9       │
│ 28.97      ┆ 3.0  ┆ Male   ┆ Yes    ┆ … ┆ Dinner ┆ 2    ┆ 10.35554        ┆ 31.97      │
│ 27.28      ┆ 4.0  ┆ Male   ┆ Yes    ┆ … ┆ Dinner ┆ 2    ┆ 14.662757       ┆ 31.28      │
│ 22.75      ┆ 3.25 ┆ Female ┆ No     ┆ … ┆ Dinner ┆ 2    ┆ 14.285714       ┆ 26.0       │
│ 22.49      ┆ 3.5  ┆ Male   ┆ No     ┆ … ┆ Dinner ┆ 2    ┆ 15.562472       ┆ 25.99      │
└────────────┴──────┴────────┴────────┴───┴────────┴──────┴─────────────────┴────────────┘

In [65]:
#Média e total de gorjetas por dia
df.group_by('day').agg([
    pl.mean('tip').alias('media_gorjeta'),
    pl.sum('tip').alias('total_gorjeta'),
    pl.count().alias('qtd_registro')
])

/tmp/ipython-input-3609731936.py:5: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias('qtd_registro')

shape: (4, 4)
┌──────┬───────────────┬───────────────┬──────────────┐
│ day  ┆ media_gorjeta ┆ total_gorjeta ┆ qtd_registro │
│ ---  ┆ ---           ┆ ---           ┆ ---          │
│ str  ┆ f64           ┆ f64           ┆ u32          │
╞══════╪═══════════════╪═══════════════╪══════════════╡
│ Fri  ┆ 2.734737      ┆ 51.96         ┆ 19           │
│ Sun  ┆ 3.255132      ┆ 247.39        ┆ 76           │
│ Thur ┆ 2.771452      ┆ 171.83        ┆ 62           │
│ Sat  ┆ 2.993103      ┆ 260.4         ┆ 87           │
└──────┴───────────────┴───────────────┴──────────────┘

In [66]:
df.group_by(['day', 'sex']).agg([
    pl.mean('tip').alias('media_gorjeta'),
    pl.sum('tip').alias('total_gorjeta'),
    pl.count().alias('qtd_registro')
])

/tmp/ipython-input-3033134755.py:4: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias('qtd_registro')

shape: (8, 5)
┌──────┬────────┬───────────────┬───────────────┬──────────────┐
│ day  ┆ sex    ┆ media_gorjeta ┆ total_gorjeta ┆ qtd_registro │
│ ---  ┆ ---    ┆ ---           ┆ ---           ┆ ---          │
│ str  ┆ str    ┆ f64           ┆ f64           ┆ u32          │
╞══════╪════════╪═══════════════╪═══════════════╪══════════════╡
│ Sun  ┆ Female ┆ 3.367222      ┆ 60.61         ┆ 18           │
│ Sat  ┆ Female ┆ 2.801786      ┆ 78.45         ┆ 28           │
│ Sun  ┆ Male   ┆ 3.220345      ┆ 186.78        ┆ 58           │
│ Thur ┆ Male   ┆ 2.980333      ┆ 89.41         ┆ 30           │
│ Fri  ┆ Male   ┆ 2.693         ┆ 26.93         ┆ 10           │
│ Thur ┆ Female ┆ 2.575625      ┆ 82.42         ┆ 32           │
│ Fri  ┆ Female ┆ 2.781111      ┆ 25.03         ┆ 9            │
│ Sat  ┆ Male   ┆ 3.083898      ┆ 181.95        ┆ 59           │
└──────┴────────┴───────────────┴───────────────┴──────────────┘

In [67]:
#Soma de valores para colunas específicas
df.select([
    pl.col('total_bill'),
    pl.col('tip'),
    pl.sum_horizontal(['total_bill', 'tip']).alias('Soma_horizontal')
]).head()

shape: (5, 3)
┌────────────┬──────┬─────────────────┐
│ total_bill ┆ tip  ┆ Soma_horizontal │
│ ---        ┆ ---  ┆ ---             │
│ f64        ┆ f64  ┆ f64             │
╞════════════╪══════╪═════════════════╡
│ 16.99      ┆ 1.01 ┆ 18.0            │
│ 10.34      ┆ 1.66 ┆ 12.0            │
│ 21.01      ┆ 3.5  ┆ 24.51           │
│ 23.68      ┆ 3.31 ┆ 26.99           │
│ 24.59      ┆ 3.61 ┆ 28.2            │
└────────────┴──────┴─────────────────┘

In [68]:
resultado = (
    df.filter(pl.col('day') == 'Sun')
    .group_by('sex')
    .agg([
        pl.mean('percent_gorgeta').alias('media_perc_gorjeta'),
        pl.sum('total_bill').alias('total_contas')
    ]).sort('media_perc_gorjeta', descending=True)
)
resultado

shape: (2, 3)
┌────────┬────────────────────┬──────────────┐
│ sex    ┆ media_perc_gorjeta ┆ total_contas │
│ ---    ┆ ---                ┆ ---          │
│ str    ┆ f64                ┆ f64          │
╞════════╪════════════════════╪══════════════╡
│ Female ┆ 18.156877          ┆ 357.7        │
│ Male   ┆ 16.234407          ┆ 1269.46      │
└────────┴────────────────────┴──────────────┘